# Site settings
title: ZihuaWeng's Blog
SEOTitle: ML study Blog
header-img: img/post-bg-desk.jpg
email: wengzihua123@126.com
description: "Share my reading notes with everyone."
keyword: "WZH, Zihuaweng Blog, image recognition, deep learning, mechine learning"
url: "http://zihuaweng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zihuaweng/zihuaweng.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Enjoy reading"
sidebar-avatar: /img/About_me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    zihuaweng
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying


# for markdown
markdown: kramdown
kramdown:
  input: GFM

# highlight codes
# highlight: true


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Je
# Gems
gems: [jekyll-paginate]



# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "xueshu.io",
        href: "http://http://linkick.com/"
    },{
        title: "简书",
        href: "http://www.jianshu.com/u/"
    }
]
